name: Build docs

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    container: 
      image: registry.jetbrains.team/p/writerside/builder/writerside-builder:2.1.984
      env:
        PRODUCT: help-module/d
        ARTIFACT: webHelpD2-all.zip
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: |  
          set -e
          /opt/builder/bin/idea.sh helpbuilderinspect -source-dir . -product $PRODUCT -output-dir artifacts/ || true
          echo "Test existing of $ARTIFACT artifact"
          test -e artifacts/$ARTIFACT
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: artifacts/webHelpD2-all.zip
          retention-days: 7
